### ISSUE TITLE
Template may not exceed 460800 bytes in size

### ISSUE THREAD

**Issue by pa** [brantburnett/terraform-aws-autoscaling-route53-srv#2]
We converted your code to CloudFormation and tried deploying it manually in AWS CloudFormation. Then it ends up with this error **Template may not exceed 460800 bytes in size**. Could you please suggest solution.

**Comment by shadycuz** [comment]
Just to be clear. It is not the "cloudformation template" its the zip file its complaining about. @PramodhAyyappan You also tried deploying lambda manually with no cloudformation involved correct? Same error?

**Comment by brantburnett** [comment]
@PramodhAyyappan That error sounds like the problem is the size of the CloudFormation template with the .zip included. I'd suggest putting the .zip on S3 independently of CloudFormation and referencing from there in your template.

**Comment by pa** [comment]
@shadycuz Thanks. It worked manually, its a problem with template url parameter in CloudFormation.

**Comment by shadycuz** [comment]
@brantburnett We did get the module to work =). It was a copy/paste error on my part when converting to cloudformation. 

Unfortuantly we can't get it to work with the pythonSDK. Could be a bug in `libcouchbase` that the pythonSDK uses. 

Logs say...
```
[ec2-user@sandboxcbfsdat1 ~]$ LCB_LOGLEVEL=5  python test.py
INFO:couchbase:Initializing Couchbase logging. lcb_version=('2.10.3', 135171)
0ms [Iccf62cb1] {8114} [INFO] (instance - L:469) Version=2.10.3, Changeset=b387722192f0bc49b0a846859610493e2f8129cd
0ms [Iccf62cb1] {8114} [INFO] (instance - L:470) Effective connection string: couchbase://bootstrap.couchbase.sandbox.example.org/MyBucket?username=Administrator. Bucket=MyBucket
3ms [Iccf62cb1] {8114} [INFO] (instance - L:146) DNS SRV lookup failed: Invalid reply received from nameserver. Ignore this if not relying on DNS SRV records
```
Record looks correct to me...

```
[ec2-user@sandboxcbfsdat1 ~]$ dig srv _couchbase._tcp.bootstrap.couchbase.sandbox.example.org

; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> srv _couchbase._tcp.bootstrap.couchbase.sandbox.example.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57484
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_couchbase._tcp.bootstrap.couchbase.sandbox.example.org. IN SRV

;; ANSWER SECTION:
_couchbase._tcp.bootstrap.couchbase.sandbox.example.org. 60 IN SRV 10 10 0 ip-10-76-21-36.ec2.internal.
_couchbase._tcp.bootstrap.couchbase.sandbox.example.org. 60 IN SRV 10 10 0 ip-10-76-21-98.ec2.internal.
_couchbase._tcp.bootstrap.couchbase.sandbox.example.org. 60 IN SRV 10 10 0 ip-10-76-20-206.ec2.internal.
_couchbase._tcp.bootstrap.couchbase.sandbox.example.org. 60 IN SRV 10 10 0 ip-10-76-20-22.ec2.internal.

;; AUTHORITY SECTION:
sandbox.example.org.       119451  IN      NS      ns-1536.awsdns-00.co.uk.
sandbox.example.org.       119451  IN      NS      ns-1024.awsdns-00.org.
sandbox.example.org.       119451  IN      NS      ns-0.awsdns-00.com.
sandbox.example.org.       119451  IN      NS      ns-512.awsdns-00.net.

;; Query time: 3 msec
;; SERVER: 10.68.10.11#53(10.68.10.11)
;; WHEN: Thu Feb 28 08:45:33 CST 2019
;; MSG SIZE  rcvd: 405
```

I did use 0 for the port. Per the couchbase docs. If you could give me your thoughts that would be greatly appreciated. 

Thanks,
Levi

Edit: Python and Node.js SDK's work when I point it to the private name from the record, but fail if I use the DNS SRV record.

**Comment by brantburnett** [comment]
@shadycuz 

I've run into trouble using port 0 before, try using port 11210 in the SRV records and see what that does.

**Comment by shadycuz** [comment]
@brantburnett You literally know more than the Couchbase Docs... 

Thanks =) All good now.
